refactor: check the commit message
- use strum::EnumVariant and strum::serialize to construct compatibility values
- Removed unused error enum variants
- Rename table-column from Checktype to Compatibility
- Schema::parse_file now accepts <P: AsRef<Path>> rather than Pathbuf

Slight improvement in the user-experience, given a wrong compatibility type:
```rust
degauss -s tests/data/movies-raw-reader.avsc tests/data/movies-raw-writer.avsc -c backward --exit-status

error: 'backward' isn't a valid value for '--compat <compat>'
	[possible values: backwards, backwards-transitive, forwards, forwards-transitive, full, full-transitive]

	Did you mean 'backwards'?

```

Rendered table now looks like this:
```
degauss -s tests/data/movies-raw-reader.avsc tests/data/movies-raw-writer.avsc -c backwards --exit-status
+---------------+--------+
| Compatibility | Status |
+========================+
| backwards     | false  |
+---------------+--------+
```